language: python
python:
  - 3.5
  - 3.6
  
install:
  - easy_install -U setuptools
  - python setup.py -q install
  - pip install codecov

script:
  - python setup.py test

after_success:
  - codecov
